name: Clima Diário por E-mail

on:
  schedule:
    - cron: '0 13 * * *'  # 10h horário de Brasília (UTC-3)
  workflow_dispatch:

jobs:
  clima-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar script
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python script.py
